name: Keyfactor Bootstrap Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, synchronize, edited, reopened]
  push:
  create:
    branches:
      - 'release-*.*'

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Checkout code
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      # Setup GoLang build environment
      # https://github.com/actions/setup-go
      - name: Set up Go 1.x
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: 'go.mod'
          cache: true

      # Download dependencies
      - run: go mod download

      # Build Go binary
      - run: go build -v .

      # Run Go linters
      # https://github.com/golangci/golangci-lint-action
      - name: Run linters
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: latest

      # Run Go tests
      - name: Run go test
        run: go test -v ./...

  call-starter-workflow:
    uses: keyfactor/actions/.github/workflows/starter.yml@v2
    needs: test
    secrets:
      token: ${{ secrets.V2BUILDTOKEN}}
      APPROVE_README_PUSH: ${{ secrets.APPROVE_README_PUSH}}
      gpg_key: ${{ secrets.KF_GPG_PRIVATE_KEY }}
      gpg_pass: ${{ secrets.KF_GPG_PASSPHRASE }}

